[package]
name = "ta_algs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["cargo"] }
fastrand = "2.1.0"
itertools = "0.13.0"
ordered-float = "4.2.0"
rand_chacha = "0.3.1"

[profile.release]
debug = true