[package]
name = "play"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.7"
fastrand = "2.1.0"
itertools = "0.13.0"
ordered-float = "4.2.0"
rand = "0.8.5"

[toolchain]
channel = "nightly"